# Project information
site_name: CAP Document
site_url: http://cap.dotnetcore.xyz
site_description: Project documentation with Markdown.
site_author: CAP Team

repo_name: 'GitHub'
repo_url: 'https://github.com/dotnetcore/CAP'

docs_dir: 'content'

# Copyright
copyright: Copyright &copy; 2017 <a href="https://github.com/dotnetcore">.NET Core Community</a>, Maintained by the <a href="/about/contact-us/#cap-team">CAP Team</a>.


#theme: material
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'indigo'  
  language: 'en'
  include_sidebar: true
  #logo: 'img/logo.png'
  #favicon: 'assets/images/favicon.ico'
  feature:
    tabs: false  
  i18n:
    prev: 'Previous'
    next: 'Next'

#Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/dotnetcore/CAP'
    - type: 'twitter'
      link: 'https://twitter.com/ncc_community'
    - type: 'weibo'
      link: 'https://weibo.com/dotnetcore'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dotnetcore
      repo: cap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# nav:
#     - Home: index.md
#     - User Guide:
#         - Getting Started: user-guide/getting-started.md
#         - API Interface: user-guide/api-interface.md
#         - Configuration: user-guide/configuration.md
#         - Design Principle: user-guide/design.md
#         - Implementation Mechanisms: user-guide/implementation.md
#         - Distributed Transactions: user-guide/transaction.md
#         - FAQ: user-guide/faq.md
#     - 使用指南:
#         - 快速开始: user-guide-cn/getting-started.md
#         - API 接口: user-guide-cn/api-interface.md
#         - 配置: user-guide-cn/configuration.md
#         - 设计原理: user-guide-cn/design-principle.md
#         - 实现: user-guide-cn/implementation.md
#         - 分布式事务: user-guide-cn/transactions.md
#         - FAQ: user-guide-cn/faq.md
#     - About:
#         - Release Notes: about/release-notes.md
#         - Contributing: about/contributing.md
#         - Contact Us: about/contact-us.md
#         - License: about/license.md
nav:
    - Getting Stared:
        - Quick Start: user-guide/cn/getting-started/quick-start.md
        - Introduction: user-guide/cn/getting-started/introduction.md
        - Contributing: user-guide/cn/getting-started/contributing.md    
    - CAP:
        - Configuration: user-guide/cn/cap/configuration.md
        - Messaging: user-guide/cn/cap/messaging.md
        - Sagas: user-guide/cn/cap/sagas.md
        - Serialization: user-guide/cn/cap/serialization.md
        - Transactions: user-guide/cn/cap/transactions.md
        - Idempotence: user-guide/cn/cap/idempotence.md
        - Upgrade Guides: user-guide/cn/cap/upgrade-guides.md
        - License: user-guide/cn/cap/license.md
    - Transports:
        - General: user-guide/cn/transports/general.md
        - RabbitMQ: user-guide/cn/transports/rabbitmq.md
        - Kafka: user-guide/cn/transports/kafka.md
        - Azure Service Bus: user-guide/cn/transports/azure-service-bus.md
        - In-Memory Message Queue: user-guide/cn/transports/in-memory-queue.md
    - Persistent:
        - General: user-guide/cn/persistent/general.md
        - SQL Server: user-guide/cn/persistent/sqlserver.md
        - MySQL: user-guide/cn/persistent/mysql.md
        - PostgreSql: user-guide/cn/persistent/postgresql.md
        - MongoDB: user-guide/cn/persistent/mongodb.md
        - In-Memory: user-guide/cn/persistent/in-memory-storage.md
    - Samples:
        - Github: user-guide/cn/samples/github.md
        - eShopOnContainers: user-guide/cn/samples/eshoponcontainers.md
        - FAQ: user-guide/cn/samples/faq.md